// ALERT
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

// AUTH
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

// ADMIN
export const CARRIERS_LOADED = 'CARRIERS_LOADED'
export const CUSTOMERS_LOADED = 'CUSTOMERS_LOADED'
export const PRIORITY_EDIT_SHOW = 'PRIORITY_EDIT_SHOW'
export const PRIORITY_EDIT_CUSTOMER_LOADED = 'PRIORITY_EDIT_CUSTOMER_LOADED'
export const ADMIN_CUSTOMER_LOADED = 'ADMIN_CUSTOMER_LOADED'

// CUSTOMER
export const CUSTOMER_LOADED = 'CUSTOMER_LOADED'
